name: testManu
favicon: null
layout_spectrum: 0.7993747922591865
typography_spectrum: 0.5907428788486868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.059451080625876784
  lightness: 0.01433550356887281
  saturation: 0.350260260514915
  rhythmicContrast: 0.015853160992264748
purpose: []
